
const errorMiddleware=(err,req,res,next)=>{

    err.message = err.message || 'internal server error';
    err.statusCode = err.statusCode || 500;
  
    //console.log(err);

    // add error messages for different2 error codes
    // if(err.code === <error code generated by database or other> ){
    //    err.message = '<your error message>',
    //    err.statusCode = '<enter response code>'
    // }
    res.status(err.statusCode).json({
        message:err.message
    });
}


export default errorMiddleware;